production: &defaults
  categories: ["Uncategorized", "Appetizers", "Breads", "Desserts", "Drinks", "Main Dishes", "Salads", "Side Dishes", "Snacks", "Soups"]

development:
  <<: *defaults

test:
  <<: *defaults